# frozen_string_literal: true

module Geo
  # In-memory spatial index over Denmark's 98 kommuner.
  #
  # Loaded once at boot from lib/geo/kommuner.geojson (see `rake geo:kommuner`)
  # and queried on every location update to decide which artist zone the car is
  # in. At 98 features behind a bounding-box prefilter a lookup is measured in
  # microseconds, so there is no need for PostGIS or a native geometry library.
  #
  # Deliberately no RGeo: it requires GEOS, and pulling a C toolchain into the
  # image to answer one question isn't a good trade. If the hand-rolled
  # containment below ever proves insufficient, `rgeo` + `libgeos-dev` can be
  # swapped in behind this same interface.
  class KommuneIndex
    GEOJSON_PATH = Rails.root.join("lib/geo/kommuner.geojson")
    ADJACENCY_PATH = Rails.root.join("lib/geo/kommune_adjacency.json")
    EXPECTED_COUNT = 98

    Kommune = Struct.new(:kode, :navn, :regionsnavn, :polygons, :bbox, keyword_init: true) do
      # polygons: [ [outer_ring, *hole_rings], ... ] — always MultiPolygon-shaped
      # bbox:     [min_lon, min_lat, max_lon, max_lat]
      def to_s = "#{kode} #{navn}"
    end

    include Singleton

    def initialize
      @kommuner = load_kommuner
    end

    attr_reader :kommuner

    # Returns the Kommune containing the point, or nil if it falls outside every
    # kommune (at sea, abroad, or on one of the small islands dropped during
    # simplification). Callers must handle nil — see Trip#current_zone, which
    # holds the previous zone rather than going silent.
    def lookup(lat:, lon:)
      @kommuner.find { |k| contains?(k, lon, lat) }
    end

    def find(kode) = @kommuner.find { |k| k.kode == kode }

    def codes = @kommuner.map(&:kode)

    # Kommune codes sharing a land border. Generated by `rake geo:adjacency`.
    #
    # Seven island kommuner (Bornholm, Samso, Laeso, Aero, Fano, Langeland,
    # Morso) have no land neighbours at all, so zone assignment cannot use
    # adjacency to force an artist change when you arrive there by ferry or
    # bridge. That is a known and accepted gap.
    def neighbours(kode) = adjacency.fetch(kode, [])

    private

    def adjacency
      @adjacency ||= begin
        unless ADJACENCY_PATH.exist?
          raise "Missing #{ADJACENCY_PATH}. Run `bin/rails geo:adjacency`."
        end

        JSON.parse(ADJACENCY_PATH.read).freeze
      end
    end

    def load_kommuner
      raise "Missing #{GEOJSON_PATH}. Run `bin/rails geo:kommuner`." unless GEOJSON_PATH.exist?

      features = JSON.parse(GEOJSON_PATH.read).fetch("features")
      kommuner = features.map { |f| build_kommune(f) }

      if kommuner.size != EXPECTED_COUNT
        raise "Expected #{EXPECTED_COUNT} kommuner in #{GEOJSON_PATH}, found #{kommuner.size}"
      end

      kommuner
    end

    def build_kommune(feature)
      props = feature.fetch("properties")
      geometry = feature.fetch("geometry")

      # mapshaper downgrades the type to Polygon when island filtering leaves a
      # feature with a single piece, so both types appear in the same file.
      # Normalise to MultiPolygon shape: [ [ring, *holes], ... ]
      polygons =
        case geometry.fetch("type")
        when "Polygon"      then [ geometry.fetch("coordinates") ]
        when "MultiPolygon" then geometry.fetch("coordinates")
        else raise "Unsupported geometry #{geometry['type']} for kommune #{props['kode']}"
        end

      Kommune.new(
        kode: props.fetch("kode"),
        navn: props.fetch("navn"),
        regionsnavn: props["regionsnavn"],
        polygons: polygons,
        bbox: bounding_box(polygons)
      )
    end

    def bounding_box(polygons)
      min_x = min_y = Float::INFINITY
      max_x = max_y = -Float::INFINITY

      polygons.each do |polygon|
        polygon.first.each do |(x, y)|
          min_x = x if x < min_x
          max_x = x if x > max_x
          min_y = y if y < min_y
          max_y = y if y > max_y
        end
      end

      [ min_x, min_y, max_x, max_y ]
    end

    def contains?(kommune, x, y)
      min_x, min_y, max_x, max_y = kommune.bbox
      return false if x < min_x || x > max_x || y < min_y || y > max_y

      kommune.polygons.any? do |polygon|
        outer, *holes = polygon
        in_ring?(outer, x, y) && holes.none? { |hole| in_ring?(hole, x, y) }
      end
    end

    # Ray casting: cast a ray east from the point and count edge crossings.
    # An odd count means the point is inside the ring.
    def in_ring?(ring, x, y)
      inside = false
      j = ring.size - 1

      ring.each_index do |i|
        xi, yi = ring[i]
        xj, yj = ring[j]

        if (yi > y) != (yj > y) && x < ((xj - xi) * (y - yi) / (yj - yi)) + xi
          inside = !inside
        end

        j = i
      end

      inside
    end
  end
end
